name: CI Pipeline with flake8 linter

on:
  push:
    branches: [ master ]

jobs:
  python-package:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.12]  

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Verify Python Version
        run: |
          python --version

      - name: Lint with flake8
        run: |
          flake8 $(find . -type f -name "*.py") || true

  docker:
    runs-on: ubuntu-latest
    needs: python-package 
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/vehicle-dealership:latest
